name: text_style_editor
description: A Flutter text style editor package.
version: 0.0.1
author: Mehdi Zarepour<mehdi.zarepoor@gmail.com>
homepage: https://github.com/mehdizarepour/text_style_editor

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Billabong
      fonts:
        - asset: packages/text_style_editor/assets/fonts/Billabong.ttf
    - family: AlexBrush-Regular
      fonts:
        - asset: packages/text_style_editor/assets/fonts/AlexBrush-Regular.ttf
    - family: Allura-Regular
      fonts:
        - asset: packages/text_style_editor/assets/fonts/Allura-Regular.otf
    - family: Arizonia-Regular
      fonts:
        - asset: packages/text_style_editor/assets/fonts/Arizonia-Regular.ttf
    - family: ChunkFive-Regular
      fonts:
        - asset: packages/text_style_editor/assets/fonts/ChunkFive-Regular.otf
    - family: GrandHotel-Regular
      fonts:
        - asset: packages/text_style_editor/assets/fonts/GrandHotel-Regular.otf
    - family: GreatVibes-Regular
      fonts:
        - asset: packages/text_style_editor/assets/fonts/GreatVibes-Regular.otf
    - family: Lobster_1.3
      fonts:
        - asset: packages/text_style_editor/assets/fonts/Lobster_1.3.otf
    - family: OpenSans-Regular
      fonts:
        - asset: packages/text_style_editor/assets/fonts/OpenSans-Regular.ttf
    - family: OstrichSans-Medium
      fonts:
        - asset: packages/text_style_editor/assets/fonts/OstrichSans-Medium.otf
    - family: Oswald-Regular
      fonts:
        - asset: packages/text_style_editor/assets/fonts/Oswald-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: packages/text_style_editor/assets/fonts/Pacifico.ttf
    - family: Quicksand-Regular
      fonts:
        - asset: packages/text_style_editor/assets/fonts/Quicksand-Regular.otf
    - family: Roboto-Regular
      fonts:
        - asset: packages/text_style_editor/assets/fonts/Roboto-Regular.ttf
    - family: SEASRN
      fonts:
        - asset: packages/text_style_editor/assets/fonts/SEASRN.ttf
    - family: Windsong
      fonts:
        - asset: packages/text_style_editor/assets/fonts/Windsong.ttf
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
